// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4XSj7iT_wvpctCwJZ1DElf1sKU-VdfA',
    appId: '1:517912732365:web:858105dd796a6c2121bf84',
    messagingSenderId: '517912732365',
    projectId: 'techwisever1',
    authDomain: 'techwisever1.firebaseapp.com',
    storageBucket: 'techwisever1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4XSj7iT_wvpctCwJZ1DElf1sKU-VdfA',
    appId: '1:517912732365:android:858105dd796a6c2121bf84',
    messagingSenderId: '517912732365',
    projectId: 'techwisever1',
    storageBucket: 'techwisever1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4XSj7iT_wvpctCwJZ1DElf1sKU-VdfA',
    appId: '1:517912732365:ios:858105dd796a6c2121bf84',
    messagingSenderId: '517912732365',
    projectId: 'techwisever1',
    storageBucket: 'techwisever1.firebasestorage.app',
    iosBundleId: 'com.example.techwisever1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB4XSj7iT_wvpctCwJZ1DElf1sKU-VdfA',
    appId: '1:517912732365:ios:858105dd796a6c2121bf84',
    messagingSenderId: '517912732365',
    projectId: 'techwisever1',
    storageBucket: 'techwisever1.firebasestorage.app',
    iosBundleId: 'com.example.techwisever1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4XSj7iT_wvpctCwJZ1DElf1sKU-VdfA',
    appId: '1:517912732365:web:858105dd796a6c2121bf84',
    messagingSenderId: '517912732365',
    projectId: 'techwisever1',
    authDomain: 'techwisever1.firebaseapp.com',
    storageBucket: 'techwisever1.firebasestorage.app',
  );
} 