name: techwisever1
description: "TechWise - แอปพลิเคชันการเรียนรู้เทคโนโลยี"
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.18
  



  cupertino_icons: ^1.0.8

  # ✅ เพิ่ม Firebase core สำหรับเชื่อม Firebase
  firebase_core: ^2.30.0

  # ✅ สำหรับการทำ Authentication (Google, Facebook, Email)
  firebase_auth: ^4.17.0

  # ✅ สำหรับ Google Sign-In (ใช้เวอร์ชันเสถียร)
  google_sign_in: ^6.1.5

  # ✅ สำหรับ Firestore database
  cloud_firestore: ^4.17.2

  # ✅ สำหรับ Firebase Storage (อัปโหลดรูปภาพ)
  firebase_storage: ^11.7.0

  # ✅ สำหรับ animations
  animate_do: ^3.3.4

  # ✅ สำหรับ local storage
  shared_preferences: ^2.2.3

  # ✅ สำหรับการเลือกรูปภาพ
  image_picker: ^1.0.4
  
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  # เพิ่มการตั้งค่าเพื่อให้ไอคอนแสดงผลชัดเจน
  adaptive_icon_padding: false
  adaptive_icon_mask: false
